// Loaded with `defer`, so the DOM is ready when this runs. Every page-specific
// feature checks for its elements first, so the same file works on every page.
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let cart=[];try{cart=JSON.parse(sessionStorage.getItem('blkm-draft-bag')||'[]')}catch{}
const euro=n=>'€'+n.toFixed(2);
function save(){try{sessionStorage.setItem('blkm-draft-bag',JSON.stringify(cart))}catch{}}
function renderCart(){$('#count').textContent=cart.reduce((a,c)=>a+c.qty,0);$('#bag-items').replaceChildren();cart.forEach((item,i)=>{const d=document.createElement('div');d.className='bag-line';const b=document.createElement('b');b.textContent=item.title+' — '+euro(item.price);const p=document.createElement('p');p.textContent=item.variants.map((v,j)=>`${j+1}. ${v.size} / ${v.color}`).join(' · ');const r=document.createElement('button');r.textContent='Remove';r.className='remove';r.onclick=()=>{cart.splice(i,1);save();renderCart()};d.append(b,p,r);$('#bag-items').append(d)});if(!cart.length)$('#bag-items').innerHTML='<p class="empty-bag">Your bag is empty. Explore the shaping briefs to try a bundle.</p>';$('#bag-total').textContent=cart.length?'Total '+euro(cart.reduce((a,c)=>a+c.price,0)):''}
renderCart();
$$('[data-dialog]').forEach(b=>b.onclick=()=>$('#'+b.dataset.dialog).showModal());
$$('dialog').forEach(d=>{d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
const infos={tracking:['Track your order','Order tracking would connect to your store’s delivery service here. This design draft has no orders or live tracking.'],shipping:['Shipping policy','The reference store lists free shipping and delivery in Italy within 7–12 business days. Replace this with your actual delivery terms before launch.'],returns:['Refunds & returns','The reference store advertises a 30-day money-back guarantee. Add your own complete return policy here before launch.'],privacy:['Privacy policy','This local draft sends no form data. Add your business’s privacy policy when you connect a real store.'],terms:['Terms of sale','This is a design reference only. No goods or services are sold here. Add your real business details and terms before launch.'],legal:['Legal notice','BLK_MAJESTY theme draft based on the supplied reference store. It is not the official reference website. Images and brand references belong to their respective owners.'],bra:['Invisible Minimizer Bra','Reference price: €29.90 (compare-at price €59.90). The original product image is retained in the collection. This draft’s complete product page is the High-Waist Shaping Briefs page.'],ebook:['The Truth About the Postpartum Belly','Reference eBook price: €14.90 (compare-at price €29.90). This preview does not provide the original eBook or accept purchases.']};
$$('[data-info]').forEach(b=>b.onclick=()=>{const [title,body]=infos[b.dataset.info];$('#info-title').textContent=title;$('#info-content').textContent=body;$('#info').showModal()});
$$('.demo-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();f.querySelector('.form-status').textContent='Preview complete. Nothing was sent or saved.'});
$$('[data-image]').forEach(b=>b.onclick=()=>{$('.main-picture img').src=b.dataset.image;$('#zoom img').src=b.dataset.image;$$('[data-image]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});
const sizes=['S','M','L','XL','2XL','3XL','4XL','5XL','6XL'];const colors=['Black','Beige','Navy Blue','Purple','Fuchsia Pink','Dark Purple','Lilac'];
$$('.variant-rows').forEach(container=>{for(let i=0;i<Number(container.dataset.count);i++){const d=document.createElement('div');d.className='variant-row';const n=document.createElement('span');n.textContent='#'+(i+1);d.append(n);for(const [label,values] of [['Size',sizes],['Color',colors]]){const s=document.createElement('select');s.setAttribute('aria-label',`${label} for brief ${i+1} in ${container.dataset.count}-piece bundle`);s.dataset.field=label.toLowerCase();values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;s.append(o)});d.append(s)}container.append(d)}});
$$('input[name=bundle]').forEach(r=>r.onchange=()=>{$$('.bundle').forEach(x=>x.classList.toggle('selected',x.contains(r)));$('#add-bundle').textContent='Add bundle to bag — '+euro(Number(r.dataset.price))});
if($('#add-bundle'))$('#add-bundle').onclick=()=>{const r=$('input[name=bundle]:checked');const variants=[...r.closest('.bundle').querySelectorAll('.variant-row')].map(d=>({size:d.querySelector('[data-field=size]').value,color:d.querySelector('[data-field=color]').value}));cart.push({title:`${r.value}-brief bundle`,qty:Number(r.value),price:Number(r.dataset.price),variants});save();renderCart();$('#bag').showModal();$('#product-status').textContent='Your selected bundle was added to the demo bag.'};
if($('.sticky-buy')&&$('#buy')){const observer=new IntersectionObserver(entries=>{$('.sticky-buy').classList.toggle('visible',!entries[0].isIntersecting&&window.scrollY>700)},{threshold:0});observer.observe($('#buy'))}
